defaultPlacement: end
enableVersioning: true
entryTypes:
  - e386913e-3a0e-4a68-b0f7-69e83d79eeb6 # pokemon
handle: pokemon
maxAuthors: 1
name: Pokemon
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  f255ef6d-0c55-4bdc-9ced-f610bbb3bed6: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: pokemon/_entry.twig
    uriFormat: 'pokemon/{slug}'
type: channel
